BookStore/BookStore.Web/Models/Book.cs
namespace BookStore.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            Carts = new HashSet<Cart>();
            OrderDetails = new HashSet<OrderDetail>();
        }
        public int BookId { get; set; }

        public int CategoryId { get; set; }

        public int AuthorId { get; set; }

        [Required]
        [StringLength(160)]
        [Display(Name = "书名")]
        public string Title { get; set; }

        [Display(Name = "单价")]
        public decimal Price { get; set; }

        [StringLength(100)]
        [Display(Name = "图片")]
        public string AlbumArtUrl { get; set; }

        [Display(Name = "详细信息")]
        public string Details { get; set; }

        public virtual Author Author { get; set; }

        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

BookStore/BookStore.Web/Controllers/BookController.cs
using BookStore.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList.Mvc;
using X.PagedList;
using System.Net;

namespace BookStore.Web.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        private BookStoreDB db = new BookStoreDB();
        public ActionResult Index(int? pageNumber)
        {
            //string sql = "select top 30 * from(select top @pageNUmber*30 * from Books orderby BookId)orderby BookId dec";

            if (pageNumber == null)
            {
                pageNumber = 1;
            }

            IPagedList<Book> list = db.Books.OrderByDescending(
            p => p.BookId).ToPagedList((int)pageNumber, 30);
            return View(list);

        }

        public ActionResult SearchBook(string bookName)
        {
            var list = db.Books.Where(b => b.Title.Contains(bookName));

            return View(list);
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book != null)
            {
                return View(book);
            }
            else
            {
                return HttpNotFound();
            }
        }

        public ActionResult ss()
        {
            return View(db.Books.ToList());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

BookStore/BookStore.Web/Controllers/ShopCartController.cs
using BookStore.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;

namespace BookStore.Web.Controllers
{
    [Authorize]
    public class ShopCartController : Controller
    {
        private BookStoreDB db = new BookStoreDB();
        // GET: ShopCart
        public ActionResult Index()
        {
           var list= db.Carts.Where(
               c => c.CartId == User.Identity.Name).OrderByDescending(
               c=>c.DateCreated).ToList();
            return View(list);
        }

        public ActionResult AddToCart(int? bookID,int? count)
        {
            if (bookID == null||count==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var book = db.Books.Find(bookID);
            if (book!=null)
            {
                var cart=  db.Carts.SingleOrDefault(c=>c.BookId==bookID&&c.CartId==User.Identity.Name);
                if (cart!=null)
                {
                    cart.Count +=(int)count;
                }
                else
                {
                    var newCart = new Cart() {
                    BookId=(int)bookID,
                    CartId=User.Identity.Name,
                    Count=(int)count,
                    DateCreated=DateTime.Now};
                    db.Carts.Add(newCart);

                }
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [AllowAnonymous]
        public ActionResult GetShopCartSummary()
        {
            int count = 0;
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    var list = db.Carts.Where(
    c => c.CartId == User.Identity.Name).ToList();

                    foreach (var item in list)
                    {
                        count += item.Count;
                    }
                }
                catch (Exception e)
                {

                    MessageBox.Show("错误"+e);
                }
            }


            ViewBag.TotalCount = count;
            return PartialView("_ShopCartSummary");
        }
        
        [HttpPost]
        public ActionResult Delete(int? recordID,string ids)
        {
            if (recordID == null)
            {
                var result = new { Status = 0 };
                return Json(result);
            }
            var item = db.Carts.SingleOrDefault(c => c.RecordId == recordID && c.CartId == User.Identity.Name);
            if (item != null)
            {
                db.Carts.Remove(item);
                db.SaveChanges();

                var total = GetTotal();
                decimal price = UpdatePrice(ids);
                var result = new {
                    Status = 1,
                    TotalPrice=price,
                    TotalCount=total.Item2};
                return Json(result);
            }
            else
            {
                var result = new { Status = 2};
                return Json(result);
            }

        }

        public ActionResult DeleteAll(string ids)
        {
            JsonResult json = new JsonResult();
            json.Data = false;
            ids = ids.Substring(0, ids.Length - 1);
            string[] id = ids.Split(',');
            for (int i = 0; i < id.Length; i++)
            {
                int recordId =int.Parse(id[i]);
                var item = db.Carts.SingleOrDefault(c => c.RecordId == recordId);
                db.Carts.Remove(item);
                db.SaveChanges();
                json.Data = true;
            }
            return Json(json.Data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UpdateCount(int? recordID,int? count,string ids)
        {
            if (recordID==null||count==null)
            {
                var result = new { Status = 0 };
                return Json(result);
            }
            var cart = db.Carts.SingleOrDefault(c => c.RecordId == recordID && c.CartId==User.Identity.Name);
            if (cart!=null)
            {
                cart.Count = (int)count;
                db.SaveChanges();

                var total = GetTotal();
                decimal price = UpdatePrice(ids);
                var result = new
                {
                    Status = 1,
                    TotalPrice = price,
                    TotalCount = total.Item2
                };
                return Json(result);
            }
            else
            {
                var result = new { Status = 2 };
                return Json(result);
            }

        }

        public decimal UpdatePrice(string ids)
        {

            decimal price = 0;

            if (ids.Length>0) {
                JsonResult json = new JsonResult();
                ids = ids.Substring(0, ids.Length - 1);
                string[] id = ids.Split(',');

                for (int i = 0; i < id.Length; i++)
                {
                    int recordId = int.Parse(id[i]);
                    var item = db.Carts.SingleOrDefault(c => c.RecordId == recordId);
                    if (item != null)
                    {
                        price += item.Book.Price * item.Count;
                    }
                }
            }

            return price;

        }
        public ActionResult UpdateTotalPrice(string ids)
        {
            decimal price = 0;

            JsonResult json = new JsonResult();
            ids = ids.Substring(0, ids.Length - 1);
            string[] id = ids.Split(',');

            for (int i = 0; i < id.Length; i++)
            {
                int recordId = int.Parse(id[i]);
                var item = db.Carts.SingleOrDefault(c => c.RecordId == recordId);
                if (item != null)
                {
                    price += item.Book.Price * item.Count;
                }
            }
            var reslut = new { TotalPrice = price };
            return Json(reslut);
            


        }
        public Tuple<decimal,int> GetTotal()
        {

            var list = db.Carts.Where(
                c => c.CartId == User.Identity.Name).ToList();

            decimal price = 0;
            int count = 0;
            foreach (var item in list)
            {
                price += item.Count * item.Book.Price;
                count += item.Count;
            }
            return new Tuple<decimal, int>(price, count);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

BookStore/BookStore.Web/Views/Book/Details.cshtml
@model BookStore.Web.Models.Book


<div style="margin-top:30px">
    <div style="float:left;margin:10px">
        <img src="@Model.AlbumArtUrl" />
    </div>
    <div style="float:left;min-width:300px">
        <h4>@Html.DisplayFor(model => model.Title)</h4>
        <hr />
        <div>价格：<span style="color:red">@Html.DisplayFor(model => model.Price)</span></div>
        @using (Html.BeginForm("AddToCart", "ShopCart", FormMethod.Get))
        {
        <input name="bookID" type="hidden" value="@Model.BookId" />
        <div>数量：<input id="count" name="count" type="text" value="1" /></div>
        <div><hr style="clear:none;border:none" /></div>
        <div><input type="submit" class="btn btn-primary"value="加入购物车" /></div>

        }        
    </div>

    <div style="clear:both">
        <hr />
    </div>
    <div>
        <h3>基本信息</h3>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Author.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Author.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Category.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Category.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
        </dl>
    </div>
    <hr />
    <div>
        <h3>内容介绍</h3>
        <p>@Html.Raw(Model.Details)</p>
    </div>
</div>

@section Scripts{
    <link href="~/Content/jquery.spinner.css" type="text/css" rel="stylesheet" />
    <script src="~/Scripts/jquery.spinner.js" type="text/javascript"></script>
    <script>
        $("#count").spinner();
    </script>

    }

BookStore/BookStore.Web/Views/Book/Index.cshtml
@using X.PagedList.Mvc
@using X.PagedList
@using BookStore.Web.Models
@model IEnumerable<Book>

@{
    ViewBag.Title = "Index";
}

<h2>BookList</h2>

<div class="row">
    @foreach (var item in Model)
    {
        <a href="~/Book/Details/@item.BookId">
        <div class="col-md-3 col-sm-4">
            <p>
                <img src="@item.AlbumArtUrl" />
            </p>
            <p>@item.Title</p>
        </div>
        </a>
    }

</div>
@Html.PagedListPager((IPagedList<Book>)Model, p => Url.Action("Index",
new { pageNumber = p }))

BookStore/BookStore.Web/Views/Book/SearchBook.cshtml
@using X.PagedList.Mvc
@using X.PagedList
@using BookStore.Web.Models
@model IEnumerable<Book>

@{
    ViewBag.Title = "SearchResult";
}

<h3>书单</h3>
<div class="row" style="padding-top:30px;">
    @foreach (var item in Model)
    {
        <a href="~/Book/Details/@item.BookId">
            <div class="col-md-3 col-sm-4">
                <p>
                    <img src="@item.AlbumArtUrl" />
                </p>
                <p>@item.Title</p>
            </div>
        </a>
    }

</div>